# Generated by Django 4.2.1 on 2023-05-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Set Title')),
                ('description', models.TextField(verbose_name='Set Text')),
            ],
            options={
                'verbose_name': 'Advantages Typography',
                'verbose_name_plural': 'Advantages Typography',
            },
        ),
        migrations.CreateModel(
            name='AdvantagesColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(verbose_name='Set Percent')),
                ('title', models.CharField(max_length=256, verbose_name='Set Title')),
            ],
            options={
                'verbose_name': 'Advantages Columns',
                'verbose_name_plural': 'Advantages Columns',
            },
        ),
        migrations.CreateModel(
            name='AdvantagesColumnsControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Set Title')),
            ],
            options={
                'verbose_name': 'Advantages Columns Control',
                'verbose_name_plural': 'Advantages Columns Control',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Portfolio Image')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Review Title')),
                ('description', models.TextField(verbose_name='Review Text')),
                ('img_f', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Review Image First')),
                ('img_s', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Review Image Second')),
                ('img_t', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Review Image Third')),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Set Title')),
                ('description', models.TextField(verbose_name='Set Text')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
