# Generated by Django 4.2.1 on 2023-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='link',
            field=models.URLField(null=True, verbose_name='Set Link'),
        ),
    ]
