# Generated by Django 4.2.1 on 2023-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0002_reviews_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='Set Whatsapp Number')),
                ('gmail', models.EmailField(max_length=254, verbose_name='Set Email')),
                ('telegram', models.CharField(max_length=50, verbose_name='Set Telegram Number')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Set Phone Number')),
                ('fl_link', models.URLField(verbose_name='Set Fl Link')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
