# Generated by Django 4.2.1 on 2023-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='icon',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Upload Icon'),
        ),
    ]
