# Generated by Django 4.2.1 on 2023-05-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0004_reviews_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='link',
            new_name='href',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='icon',
            new_name='userIcon',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='title',
            new_name='userName',
        ),
    ]
