# Generated by Django 4.2.1 on 2023-05-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0005_rename_description_reviews_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvantagesColumns',
        ),
        migrations.DeleteModel(
            name='AdvantagesColumnsControl',
        ),
        migrations.AddField(
            model_name='advantages',
            name='charachters_col_first',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Charachter Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='charachters_col_fiveth',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Charachter Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='charachters_col_fourth',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Charachter Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='charachters_col_second',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Charachter Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='charachters_col_sixth',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Charachter Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='charachters_col_third',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Charachter Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='charachters_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Charachters Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='col_f',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='col_f_description',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Column First Description'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='col_s',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Column Second Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='col_s_description',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Column Second Description'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='col_t',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Column Third Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='col_t_description',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Column Third Description'),
        ),
    ]
