# Generated by Django 4.2.1 on 2023-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0006_delete_advantagescolumns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantages',
            name='charachters_col_first',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='charachters_col_fiveth',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='charachters_col_fourth',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='charachters_col_second',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='charachters_col_sixth',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='charachters_col_third',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='col_f',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='col_f_description',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='col_s',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='col_s_description',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='col_t',
        ),
        migrations.RemoveField(
            model_name='advantages',
            name='col_t_description',
        ),
        migrations.AddField(
            model_name='advantages',
            name='characters_column_first',
            field=models.CharField(max_length=265, null=True, verbose_name='Set Characters Column First Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='characters_column_fiveth',
            field=models.CharField(max_length=265, null=True, verbose_name='Set Characters Column Fiveth Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='characters_column_fourth',
            field=models.CharField(max_length=265, null=True, verbose_name='Set Characters Column Fourth Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='characters_column_second',
            field=models.CharField(max_length=265, null=True, verbose_name='Set Characters Column Second Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='characters_column_sixth',
            field=models.CharField(max_length=265, null=True, verbose_name='Set Characters Column Sixth Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='characters_column_third',
            field=models.CharField(max_length=265, null=True, verbose_name='Set Characters Column Third Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='develope_column',
            field=models.CharField(max_length=256, null=True, verbose_name='Set Marketing Column Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='developer_column_percent',
            field=models.IntegerField(null=True, verbose_name='Set Develop Column Percent'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='experience_column',
            field=models.CharField(max_length=256, null=True, verbose_name='Set Experience Column Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='experience_column_percent',
            field=models.IntegerField(null=True, verbose_name='Set Experience Column Percent'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='marketing_column',
            field=models.CharField(max_length=256, null=True, verbose_name='Set Marketing Column Title'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='marketing_column_percent',
            field=models.IntegerField(null=True, verbose_name='Set Marketing Column Percent'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='charachters_title',
            field=models.CharField(max_length=256, null=True, verbose_name='Set Charachters Title'),
        ),
    ]
