# Generated by Django 4.2.1 on 2023-05-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0007_remove_advantages_charachters_col_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advantages',
            old_name='developer_column_percent',
            new_name='develope_column_percent',
        ),
    ]
