# Generated by Django 4.2.1 on 2023-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0008_rename_developer_column_percent_advantages_develope_column_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, verbose_name='Set Title')),
                ('title', models.CharField(max_length=256, verbose_name='Set Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Page Control',
                'verbose_name_plural': 'Page Control',
            },
        ),
    ]
