# Generated by Django 4.2.1 on 2023-05-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0009_basic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='page_name',
        ),
        migrations.AddField(
            model_name='basic',
            name='logo',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Upload Logo'),
        ),
    ]
