# Generated by Django 4.2.1 on 2023-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0010_remove_basic_page_name_basic_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='background_image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Background Image'),
        ),
    ]
