# Generated by Django 4.2.1 on 2023-05-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0012_remove_basic_background_image_basic_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='video',
        ),
    ]
