# Generated by Django 4.2.1 on 2023-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0015_remove_contact_fl_link_contact_fl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('email', models.CharField(max_length=256, verbose_name='Email')),
                ('phone', models.CharField(max_length=256, verbose_name='Phone')),
                ('message', models.CharField(max_length=256, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
