# Generated by Django 4.2.1 on 2023-05-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0016_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='basic',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='basic',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='contact',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='contact',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='etaps',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='etaps',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='message',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='message',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='services',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='services',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
    ]
