# Generated by Django 4.2.1 on 2023-05-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0018_advantagesen_advantagesru_basicen_basicru_etapsen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesru',
            options={'verbose_name': 'Услуги RU', 'verbose_name_plural': 'Услуги RU'},
        ),
    ]
