# Generated by Django 4.2.1 on 2023-05-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0019_alter_servicesru_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesen',
            options={'verbose_name': 'Услуги EN', 'verbose_name_plural': 'Услуги EN'},
        ),
    ]
