# Generated by Django 4.2.1 on 2023-05-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0020_alter_servicesen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.RemoveField(
            model_name='etapsen',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='etapsru',
            name='page_title',
        ),
        migrations.AlterField(
            model_name='etapsen',
            name='action_first_title',
            field=models.CharField(max_length=256, verbose_name='Установить первым заголовок действия:'),
        ),
        migrations.AlterField(
            model_name='etapsen',
            name='actions_title',
            field=models.CharField(max_length=256, verbose_name='Установить название Набор действий:'),
        ),
        migrations.AlterField(
            model_name='etapsru',
            name='action_first_title',
            field=models.CharField(max_length=256, verbose_name='Установить первым заголовок действия:'),
        ),
        migrations.AlterField(
            model_name='etapsru',
            name='actions_title',
            field=models.CharField(max_length=256, verbose_name='Установить название Набор действий:'),
        ),
    ]
