# Generated by Django 4.2.1 on 2023-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0021_alter_portfolio_options_remove_etapsen_page_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicen',
            options={'verbose_name': 'Главная Страница EN', 'verbose_name_plural': 'Главная Страница EN'},
        ),
        migrations.AlterModelOptions(
            name='basicru',
            options={'verbose_name': 'Главная Страница RU', 'verbose_name_plural': 'Главная Страница RU'},
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=256, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=256, verbose_name='Phone'),
        ),
    ]
