# Generated by Django 4.2.1 on 2023-05-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dh_code', '0022_alter_basicen_options_alter_basicru_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='message',
            name='time_update',
        ),
    ]
